### ISSUE TITLE
Item Details Layout 1 Issues:

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#39]
- Dynamic links are not clickable
- Dynamic link text and icon color should be pulled from primary links and buttons
- Distance indication does not work

**Comment by vineetasharma** [comment]
Fixed the issue. Please check it.

**Comment by nathankeating** [comment]
CONFIRMED FIXED
- Dynamic links are not clickable
- Distance indication does not work

NOT FIXED
- Dynamic link text and icon color should be pulled from primary links and buttons
The icons for the dynamic links are pulling from the primary color, but the text is not.

**Comment by vineetasharma** [comment]
@nathankeating  Fixed the issue. Please Check.

**Comment by nathankeating** [comment]
Confirmed
