### ISSUE TITLE
Item Details Layout 3 Issues:

### ISSUE THREAD

**Issue by nathankeating** [BuildFire/placesPlugin#41]
- Map overlay text should be pulled from the title bar text (see screenshot)
- Address should be clickable to take the user to their native maps app (see screenshot)
- Address title should replace the address. Currently, it is adding to the beginning of the address (see screenshot)
- Carousel Images should all be 16x9 ratio with all corners rounded and should automatically scroll through (see screenshot)

Here's what it looks like:
<img width="386" alt="screen shot 2015-10-13 at 10 33 58 pm" src="https://cloud.githubusercontent.com/assets/6145369/10475639/8959900c-71fa-11e5-86ae-a88f3e83a752.png">

Here's what it should look like:
![item details layout 3](https://cloud.githubusercontent.com/assets/6145369/10475666/be39415a-71fa-11e5-9576-90a58fe7dd3f.png)

**Comment by vineetasharma** [comment]
@nathankeating  Still following function is remaining.
>Address should be clickable to take the user to their native maps app .

**Comment by vineetasharma** [comment]
This issue is fixed. Please check this.

**Comment by nathankeating** [comment]
I am not seeing any of these items fixed

**Comment by nathankeating** [comment]
All issues are still in effect

**Comment by vineetasharma** [comment]
Fixed the followings issue:
1. Map overlay text should be pulled from the title bar text.
2. Address should be clickable to take the user to their native maps app (On INT Tested).
3. Address title should replace the address. Currently, it is adding to the beginning of the address.

**Comment by vineetasharma** [comment]
@nathankeating Fixed the issue. Please Check now.

**Comment by nathankeating** [comment]
Not fixed. This is what I see on mobile. Please review on mobile as well.
![img_8912](https://cloud.githubusercontent.com/assets/6145369/10983723/22a8ba1e-83c9-11e5-882d-5cafad98a611.PNG)
